version: "3.7"

services:
  app:
    build: .
    container_name: microservice-app
    depends_on:
      - db
      - kafka
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/applications
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8000:8000"
    networks:
      - microservice-network

  db:
    image: postgres:13
    container_name: microservice-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=applications
    ports:
      - "5432:5432"
    networks:
      - microservice-network

  kafka:
    image: wurstmeister/kafka
    container_name: microservice-kafka
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092  # Слушать все интерфейсы на порту 9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://microservice-kafka:9093  # Рекламировать как доступный на microservice-kafka:9093 (имя контейнера или сервис)
      - KAFKA_LISTENER_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9093:9093"  # Пробрасываем порт 9093 на хост
    networks:
      - microservice-network



  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: microservice-zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
